version: '3'

services:
  webapicoreexemplo:
    image: webapicoreexemplo
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - demo_aspnet
  
  meu_mongo:
    image: mongo
    # ports:
    #   - "27017:27017"
    volumes:
      - db_mongo:/data/db
    networks:
      - demo_aspnet
    restart: always
    command: --storageEngine wiredTiger
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: exemplo

volumes: 
  db_mongo:

networks:
  demo_aspnet:
    driver: bridge